services:
  acmedns:
    build: .
    restart: always
    environment:
      DOMAIN: ${DOMAIN:?}
      NSNAME: ${NSNAME:?}
      NSADMIN: ${NSADMIN:?}
      PUBLIC_IP: ${PUBLIC_IP:?}
      PUBLIC_PORT: ${PUBLIC_PORT:-8443}
      API_LISTEN_PORT: ${API_LISTEN_PORT:-443}
      API_TLS: ${API_TLS:-letsencryptstaging}
      NOTIFICATION_EMAIL: ${NOTIFICATION_EMAIL}
    ports:
      - "${PUBLIC_PORT:-8443}:${API_LISTEN_PORT:-443}"
      - "53:53"
      - "53:53/udp"
    volumes:
      - ./data:/var/lib/acme-dns